"""Spec-derived tests generated by run_full_file_probe.py.

The model does not write this file. It is the independent oracle for
the current strict full-file probe run.
"""

from hands_probe.text_tools import dedupe_candidates_by_email, extract_candidate_names, filter_candidates_by_company, format_candidate_report, group_candidate_names_by_company, has_complete_contact

def test_contact_quality_oracle_requires_both_non_blank_fields():
    assert has_complete_contact({"email": "a@example.com", "phone": "+1"}) is True
    assert has_complete_contact({"email": "a@example.com", "phone": "   "}) is False
    assert has_complete_contact({"email": "   ", "phone": "+1"}) is False
    assert has_complete_contact({"email": None, "phone": "+1"}) is False
    assert has_complete_contact({"phone": "+1"}) is False

def test_candidate_names_oracle_strips_skips_and_preserves_order():
    candidates = [
        {"name": "  Ivan Petrov  "},
        {"name": None},
        {"email": "missing-name@example.com"},
        {"name": ""},
        {"name": "Anna"},
        {"name": "Ivan Petrov"},
        {"name": "   "},
    ]

    assert extract_candidate_names(candidates) == [
        "Ivan Petrov",
        "Anna",
        "Ivan Petrov",
    ]

def test_company_filter_oracle_matches_without_copying_or_mutating():
    first = {"name": "Ivan", "company": " Megalift "}
    second = {"name": "Anna", "company": "MEGALIFT"}
    ignored = {"name": "No Company", "company": None}
    candidates = [first, ignored, {"name": "Other", "company": "Acme"}, second]

    result = filter_candidates_by_company(candidates, "megalift")

    assert result == [first, second]
    assert result[0] is first
    assert result[1] is second
    assert filter_candidates_by_company(candidates, "   ") == []

def test_email_dedupe_oracle_keeps_first_normalized_email_identity():
    first = {"name": "Ivan", "email": " Ivan@Example.com "}
    duplicate = {"name": "Ivan Duplicate", "email": "ivan@example.com"}
    second = {"name": "Anna", "email": "anna@example.com"}
    candidates = [
        {"name": "No Email"},
        first,
        {"name": "Blank", "email": "   "},
        duplicate,
        second,
        {"name": "None", "email": None},
        {"name": "Anna Duplicate", "email": " ANNA@EXAMPLE.COM "},
    ]

    result = dedupe_candidates_by_email(candidates)

    assert result == [first, second]
    assert result[0] is first
    assert result[1] is second

def test_company_name_groups_oracle_normalizes_and_skips_blank_values():
    candidates = [
        {"name": " Ivan ", "company": " MEGALIFT "},
        {"name": "Anna", "company": "megalift"},
        {"name": "No Company", "company": "   "},
        {"name": "", "company": "Acme"},
        {"company": "Acme"},
        {"name": "Bob", "company": "ACME"},
        {"name": "Ivan", "company": "Megalift"},
    ]

    assert group_candidate_names_by_company(candidates) == {
        "megalift": ["Ivan", "Anna", "Ivan"],
        "acme": ["Bob"],
    }

def test_candidate_report_oracle_formats_lines_and_skips_fully_blank_records():
    candidates = [
        {
            "name": " Ivan ",
            "company": " Megalift ",
            "email": "ivan@example.com",
            "phone": " +1 ",
        },
        {"name": None, "company": "Acme", "email": "   ", "phone": None},
        {"name": "   ", "company": "   ", "email": "x@example.com", "phone": "+2"},
        {"name": "Anna", "company": None, "email": None, "phone": "   "},
    ]

    assert format_candidate_report(candidates) == "\n".join(
        [
            "Ivan - Megalift - ivan@example.com, +1",
            "Unknown candidate - Acme - no contact",
            "Anna - Unknown company - no contact",
        ]
    )
    assert format_candidate_report([]) == ""
